# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 01 Apr 2015 00:09:06 +0000
*	@ALL	0
*	@user	0
*	@internal	1
home	@ALL	1
hosts-event:*	@host%2dcurrent	1
hosts-guidelines:*	@host%2dapplicant	1
hosts-planning:*	@host%2dcurrent	1
hosts-aftercare:*	@host%2dcurrent	1
hosts-guidelines:*	@host%2dcurrent	1
